# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - fla-applications-upload-utility-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
      id-token: write #This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and generate Prisma
        run: |
          cd backend
          npm install
          npx prisma generate

      - name: Remove node_modules (Azure will reinstall)
        run: |
          cd backend
          rm -rf node_modules
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D75999CD59634C108099E2B1C6811944 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_58571E2FEB8940879D795CD5B3DD7E6D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B0825C2A56934B109FF50C11165454E4 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fla-applications-upload-utility-backend'
          slot-name: 'Production'
          package: ./backend
          